# 1) Write a program to create a 5 dimensional array with all zeros and ones

In [8]:
import numpy as np
np.array([[0,0,0,0,0],[1,1,1,1,1]],ndmin=5)

array([[[[[0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1]]]]])

# 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [2]:
import numpy as np
np.array([[[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]]])

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]])

# 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [2]:
import numpy as np
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [11]:
import numpy as np
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [13]:
import numpy as np
a=np.arange(1,17).reshape(4,4)
a[:,[0,1]]=a[:,[-1,0]]
a[:,[1,2]]=a[:,[2,1]]
a

array([[ 4,  3,  1,  4],
       [ 8,  7,  5,  8],
       [12, 11,  9, 12],
       [16, 15, 13, 16]])

# 6) Write a program to reverse an array (the first element becomes the last).Given array:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [4]:
import numpy as np
x=np.arange(12,28)
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100



In [14]:
import numpy as np
x=np.arange(1,101).reshape(10,10)
x=x[x%5==0]
x=x[x>30]
x=x[x<80]
x

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# 8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [1]:
import numpy as np
arr1=np.ones((9,9),dtype=int)
arr1[1:8,1:8]=0
arr1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

#  9) Write a program to create a checkerboard pattern .Don't use default array function


# 10) Write a program to find common values between two arrays.
# Expected Output:
# array1: [10 20 40 60]
# array2: [10, 30, 40,50]


In [9]:
import numpy as np
x=np.array([[10,20,40,60]])
y=np.array([[10,30,40,60]])
np.intersect1d(x,y)

array([10, 40, 60])

# 11) Write a program to create an array 2d array and then reshape into 1d array


In [5]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions